outdoor_maps_builder_node:
  ros__parameters:
    sensor_topic: "/map"
    map_types: ["pcl", "gridmap"]

    pcl:
      downsample_resolution: 1.0
      perception_default_frame: "map"

    gridmap:
      downsample_resolution: 1.0
      perception_default_frame: "map"
