controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [vff]
    vff:
      plugin: easynav_vff_controller/VffController
      distance_obstacle_detection_: 3.0
      distance_to_goal_: 1.0
      obstacle_detection_x_min_: 0.5
      obstacle_detection_x_max_: 10.0
      obstacle_detection_y_min_: -10.0
      obstacle_detection_y_max_: 10.0
      obstacle_detection_z_min_: 0.1
      obstacle_detection_z_max_: 1.0
      max_speed_: 0.5
      max_angular_speed_: 1.5

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [gps]
    gps:
      plugin: easynav_gps_localizer/GpsLocalizer

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [lidar]
    perception_default_frame: odom
    lidar:
      topic: /front_laser_sensor/points
      type: PointCloud

